### ISSUE TITLE
SVG versions of logo

### ISSUE THREAD

**Issue by joemoraca** [Podcastindex-org/art-graphics-logos#1]
I made an SVG version of the banner logo.  SVG is good because you can scale it to any size and not get pixelation ..

https://github.com/joemoraca/podcastindex-logos/blob/master/podcastindexbanner2.svg

**Comment by jamescridland** [comment]
This is excellent, Joe, thank you.

I wonder if you'd be so kind as to make an SVG version of the icon, too?

**Comment by jamescridland** [comment]
(PS: Also, it would be excellent if you'd submit a pull request so that they can be added here)

**Comment by daveajones** [comment]
@joemoraca Could you fork this and do a pull request to add?

**Comment by joemoraca** [comment]
I will do that.today. I am sort of new to github.

**Comment by podcastindex** [comment]
No worries Joe.  Shoot it to me in an email if you need to.

**Comment by joemoraca** [comment]
I figured it out.  Thanks for your efforts.

**Comment by daveajones** [comment]
This is excellent Joe.  Thank you so much.
